### ISSUE TITLE
defineORs(job)

### ISSUE THREAD

**Issue by m-amrei** [ORTools4MTEX/ORTools#12]
Dear Frank, 

I am trying to use this example on my own EBSD analysis however, there is no Beta in my materials which leads the defineORs(job) to go to isempty condition. So I get this window asking me to define an OR using Miller-Bravais indices: 
![image](https://user-images.githubusercontent.com/59927140/165589612-00961f01-1c0e-4c62-8246-30bd56fe4079.png)
What would be the proper values?
Regards, 
Mohsen

**Comment by AzdiarGazder** [comment]
Hi Mohsen,

I assume you are working on an alpha Ti alloy and trying to reconstruct the parent beta phase. In this case, you would like to begin the process by assuming the Burgers OR is the operative rational OR. To do this, please input the following in the GUI window:

Parent bcc theoretical plane and direction
hkl_bcc = [1 -1 0]; uvw_bcc = [1 1 1];

Child hcp theoretical plane and direction
HKIL = [0 0 0 1]; UVTW = [1 1 -2 0];

As you can imagine, the above is only 1 representation of the Burgers OR.
It follows that any other combination that fulfills the Burgers OR can be used as well.

Hope this helps.

Warm regards,
Azdi
