### ISSUE TITLE
ORTools-Example 2-Parent Grain Reconstruction in Titanium alloys error

### ISSUE THREAD

**Issue by biginnerMTEX** [ORTools4MTEX/ORTools#3]
Hello.

I have trouble when I practice with ORTools-Example2-Paraent grain reconstruction in titanium alloys

Actually, the it is the same problem with Naga Chaitanya in comment.
I am also when I doing peak fitting(3:36 of video)

Undefined function 'findpeaks' for input arguments of type
'double'.

Error in gaussFit (line 46)
    [peakValue,peakPositionIdx,peakWidth,peakHeight] = findpeaks(y,
    'MinPeakDist',classInterval.fine,
    'MinPeakHeight',ypos,'Annotate','extents','WidthReference','halfheight');

Error in defineORs (line 45)
            [misoRange] =
            gaussFit(classRange,classInterval,counts);

Error in ORTools_example2 (line 54)
job = defineORs(job);

this error is occurred.
How can I solve this problem? 

thank you and have a nice day

**Comment by frankNiessen** [comment]
Hi, 

as stated in the readme, you need the Signal Processin Toolbox for the peak fitting functionality. The command `which findpeaks` in MATLAB returns the following on my system: 

`C:\Program Files\MatLab R2020a\toolbox\signal\signal\findpeaks.m`

This tells me that the function exists and that it is part of the signal processing toolbox in MATLAB. If you don't get any return value, you don't have the toolbox installed and cannot use this functionality.

Cheers
Frank

**Comment by biginnerMTEX** [comment]
I am really appreciated that your help and I have solved the problem!

Thanks
