### ISSUE TITLE
How to export .cpr file after phase reconstruction

### ISSUE THREAD

**Issue by biginnerMTEX** [ORTools4MTEX/ORTools#4]
Hello.
I want to export .cpr file to re-analysis in Aztec program.
I tried .ctf file format and it was possible by this job.ebsd.export('filename.ctf')
However, there is a problem when I export .cpr format
Actually, I can not understand meaning of the Pfname in this Syntax export_crc(ebsd,Pfname)
I am waiting your reply and have a nice day.

Thanks,

**Comment by frankNiessen** [comment]
As far as I know the export to crc is still somewhat of an experimental feature - it does not work in all cases (it depends on which file type you import in). You can always import a ctf file to the OI Project manager and then save it to cpr/crc to open it in Aztec, I think. 

In the future I would like to ask you to post issues that are related to MTEX in general into the [MTEX forum](https://github.com/mtex-toolbox/mtex/issues), as this is an MTEX issue, not an ORTools issue.
