### ISSUE TITLE
Error: File: plotIPDF_gB_prob.m Line: 113 Column: 18

### ISSUE THREAD

**Issue by m-amrei** [ORTools4MTEX/ORTools#8]
hello 

Error: File: plotIPDF_gB_prob.m Line: 113 Column: 18
Invalid text character. Check for unsupported symbol, invisible character, or pasting of non-ASCII characters.
Regards, 

Mohsen

**Comment by frankNiessen** [comment]
Dear Mohsen, 

thank you for pointing this out. The file seems to have been damaged during the last commit. It is fixed now and can be found here:
https://github.com/ORTools4MTEX/ORTools/blob/develop/src/plotIPDF_gB_prob.m
